FROM node:20-alpine as build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

COPY ./ssl/fixmycar.2bd.net /etc/ssl/fixmycar

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
